### ISSUE TITLE
Add the ability to disable geodesic logic

### ISSUE THREAD

**Issue by alexander-gush** [zakjan/mapbox-gl-draw-geodesic#34]
I believe this library has the best out of the box solution for drawing a circle for Mapbox.

But could you consider disabling the geodesic logic for those who only need a circle.
Or maybe you can suggest how I can do it myself?

**Comment by zakjan** [comment]
Hi @alexander-gush , the geodesic logic is needed for drawing circles, otherwise they are not computed correctly.
